cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    akb@admin:
      email: test@gmail.com
      failed_login_attempts: 0
      first_name: akb
      last_name: admin
      logged_in: False
      password: $2b$12$B6G1cfYSpFzdAVs83wu.O.NAgXCEfqfGNQMCRfuMsM01faTY922r6
      roles:
      - admin
